# -*- coding: utf-8 -*-
"""Multi_ camera_classbased.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r6bXrzJ3_HLvF3oplhjlUD1oc-QWfITJ
"""

!pip install ultralytics opencv-python deep-sort-realtime

# -*- coding: utf-8 -*-
"""Multi-Camera PPE Detection System

Supports multiple cameras: video files, webcam indices, and IP/RTSP streams
"""

import cv2
import time
import datetime
import numpy as np
from pathlib import Path
from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort
import argparse
from google.colab.patches import cv2_imshow
import math


# ----------------------------
# CONFIG
# ----------------------------

DEFAULT_REQUIRED_PPE = {"helmet", "shoes", "goggles", "safety_vest", "pvc_suit", "Safety_Gloves"}

ALIASES = {
    "person": {"person", "Person"},
    "helmet": {"helmet", "hardhat", "safety_helmet", "Helmet"},
    "safety_vest": {"vest", "safety_vest", "Safety_Vestr"},
    "no_helmet": {"no_helmet", "no_safety_helmet", "no_hardhat", "NO_helmet"},
    "no_safety_vest": {"no_vest", "no_safety_vest", "NO_Vestr"},
    "pvc_suit": {"pvc_suit", "suit"},
    "no_pvc_suit": {"no_pvc_suit", "no_suit"},
    "shoes": {"shoes", "safety_shoes", "boots", "Safety Shoes"},
    "goggles": {"goggles", "safety_goggles", "glasses", "eye_protection", "Safety Goggles"},
    "no_safety_shoes": {"no_shoes", "NO_safetyshoes", "no_boots", "no_safety_shoes"},
    "no_goggles": {"no_goggles", "NO_goggles", "no_eye_protection", "no_safety_goggles"},
    "Safety_Gloves": {"Safety_Gloves", "Gloves"},
    "No_Gloves": {"No_Gloves", "NO_Gloves", "No_Safety_Gloves"},
}

CLR_OK = (0, 200, 0)
CLR_MISS = (0, 0, 255)

# ----------------------------
# Helper Functions
# ----------------------------

def canonicalize(name: str) -> str:
    n = name.lower().replace(" ", "_")
    for canon, synonyms in ALIASES.items():
        if n == canon or n in synonyms:
            return canon
    return n

def center_of_box(xyxy):
    x1, y1, x2, y2 = xyxy
    return (int((x1 + x2) / 2), int((y1 + y2) / 2))

def inside_bbox(point, bbox):
    px, py = point
    x1, y1, x2, y2 = bbox
    return x1 <= px <= x2 and y1 <= py <= y2

def ensure_log_file(path):
    if not Path(path).exists():
        with open(path, "w") as f:
            f.write("--- PPE VIOLATION LOG ---\n")
            f.write("Timestamp           | Camera | Person ID | Missing PPE\n")
            f.write("--------------------+--------+-----------+-----------------\n")

def parse_video_source(source):
    """Parse video source to determine if it's a file, webcam index, or RTSP URL"""
    # Check if it's a number (webcam index)
    try:
        return int(source)
    except ValueError:
        pass

    # Check if it's an RTSP/HTTP URL
    if source.startswith(('rtsp://', 'http://', 'https://')):
        return source

    # Otherwise treat as file path
    return source

def calculate_grid_layout(num_cameras):
    """Calculate optimal grid layout for multiple cameras"""
    if num_cameras == 1:
        return 1, 1
    elif num_cameras == 2:
        return 1, 2
    elif num_cameras <= 4:
        return 2, 2
    elif num_cameras <= 6:
        return 2, 3
    elif num_cameras <= 9:
        return 3, 3
    elif num_cameras <= 12:
        return 3, 4
    else:
        return 4, 4

def resize_frame_to_fit(frame, target_width, target_height):
    """Resize frame to fit target dimensions while maintaining aspect ratio"""
    h, w = frame.shape[:2]

    # Calculate scaling factor
    scale = min(target_width / w, target_height / h)

    new_w = int(w * scale)
    new_h = int(h * scale)

    # Resize frame
    resized = cv2.resize(frame, (new_w, new_h))

    # Create canvas with black background
    canvas = np.zeros((target_height, target_width, 3), dtype=np.uint8)

    # Center the resized frame on canvas
    y_offset = (target_height - new_h) // 2
    x_offset = (target_width - new_w) // 2

    canvas[y_offset:y_offset+new_h, x_offset:x_offset+new_w] = resized

    return canvas

# ----------------------------
# Camera Processing Class
# ----------------------------

class CameraProcessor:
    def __init__(self, camera_id, source, model, tracker, args, required_ppe, detect_class_indices):
        self.camera_id = camera_id
        self.source = source
        self.model = model
        self.tracker = tracker
        self.args = args
        self.required_ppe = required_ppe
        self.detect_class_indices = detect_class_indices

        # Open video source
        self.cap = cv2.VideoCapture(source)
        if not self.cap.isOpened():
            raise ValueError(f"Cannot open camera source: {source}")

        # Get camera properties
        self.width = int(self.cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        self.height = int(self.cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        self.fps = self.cap.get(cv2.CAP_PROP_FPS)
        if self.fps == 0 or self.fps > 120:  # Handle invalid FPS
            self.fps = 30

    def process_frame(self):
        """Process a single frame from this camera"""
        ret, frame = self.cap.read()
        if not ret:
            return None

        # Run YOLO detection
        results = self.model.predict(
            frame,
            conf=self.args.conf,
            iou=self.args.iou,
            classes=self.detect_class_indices,
            verbose=False
        )

        dets = results[0].boxes
        detections_for_tracker = []
        ppe_items = []

        if dets is not None and len(dets) > 0:
            for i in range(len(dets)):
                xyxy = dets.xyxy[i].cpu().tolist()
                cls_id = int(dets.cls[i].cpu().item())
                conf = float(dets.conf[i].cpu().item())
                class_name = canonicalize(self.model.names.get(cls_id, ""))

                if class_name == "person":
                    w, h = xyxy[2] - xyxy[0], xyxy[3] - xyxy[1]
                    detections_for_tracker.append(([xyxy[0], xyxy[1], w, h], conf, class_name))
                else:
                    if conf >= self.args.conf:
                        ppe_items.append({"center": center_of_box(xyxy), "name": class_name})

        # Update tracker
        tracks = self.tracker.update_tracks(detections_for_tracker, frame=frame)

        # Draw detections
        for track in tracks:
            if not track.is_confirmed():
                continue

            track_id = track.track_id
            ltrb = track.to_ltrb()
            px1, py1, px2, py2 = map(int, ltrb)

            # Determine PPE status
            owned_ppe = {item["name"] for item in ppe_items if inside_bbox(item["center"], ltrb)}
            missing_items = set()
            present_items = set()

            for required_item in self.required_ppe:
                if required_item in owned_ppe:
                    present_items.add(required_item)
                elif f"no_{required_item}" in owned_ppe:
                    missing_items.add(required_item)
                else:
                    missing_items.add(required_item)

            # Draw bounding box
            color = CLR_MISS if missing_items else CLR_OK
            cv2.rectangle(frame, (px1, py1), (px2, py2), color, 2)

            # Draw PPE status
            x, y = px1, py1 - 10
            base_text = f"ID: {track_id} PPE:"
            font = cv2.FONT_HERSHEY_SIMPLEX
            scale = 0.6
            thickness = 2

            # Draw base text with background
            text_size = cv2.getTextSize(base_text, font, scale, thickness)[0]
            overlay = frame.copy()
            cv2.rectangle(overlay, (x-2, y-16), (x + text_size[0] + 4, y+6), (0,0,0), -1)
            alpha = 0.6
            frame = cv2.addWeighted(overlay, alpha, frame, 1 - alpha, 0)
            cv2.putText(frame, base_text, (x, y), font, scale, (255,255,255), thickness)

            offset_x = x + text_size[0] + 10

            # Draw individual PPE items
            for item in sorted(list(self.required_ppe)):
                if item in present_items:
                    status = "OK"
                    text_color = (0, 200, 0)
                else:
                    status = "MISSING"
                    text_color = (0, 0, 255)

                text = f" {item}:{status}"
                tsize = cv2.getTextSize(text, font, scale, thickness)[0]
                overlay = frame.copy()
                cv2.rectangle(overlay, (offset_x-2, y-16), (offset_x + tsize[0] + 4, y+6), (0,0,0), -1)
                frame = cv2.addWeighted(overlay, alpha, frame, 1 - alpha, 0)
                cv2.putText(frame, text, (offset_x, y), font, scale, text_color, thickness)
                offset_x += tsize[0] + 10

            # Log violations
            if missing_items and self.args.log:
                timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                missing_str = ", ".join(sorted(list(missing_items)))
                log_entry = f"{timestamp} | Cam {self.camera_id} | {track_id:<9} | {missing_str}\n"
                with open(self.args.log, "a") as f:
                    f.write(log_entry)

        # Add camera label
        label_text = f"Camera {self.camera_id}"
        cv2.putText(frame, label_text, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2)

        return frame

    def release(self):
        """Release camera resources"""
        self.cap.release()

# ----------------------------
# Main Detection Logic
# ----------------------------

def main(args):
    if args.log:
        ensure_log_file(args.log)

    # Load model
    try:
        model = YOLO(args.model)
    except Exception as e:
        print(f"Error loading model: {e}")
        return

    # Parse video sources
    video_sources = []
    if args.cameras:
        for source in args.cameras:
            video_sources.append(parse_video_source(source))
    else:
        video_sources.append(parse_video_source(args.video))

    num_cameras = len(video_sources)
    print(f"Processing {num_cameras} camera(s)")

    # Setup PPE detection classes
    detect_classes_names = set()
    required_ppe = set()

    if args.classes:
        print(f"User specified classes: {args.classes}")
        user_ppe_types = set()
        for cls_name in args.classes:
            canon_name = canonicalize(cls_name)
            if canon_name.startswith("no_"):
                user_ppe_types.add(canon_name[3:])
            else:
                user_ppe_types.add(canon_name)

        required_ppe = user_ppe_types
        print(f"Required PPE for all zones set to: {required_ppe}")

        for ppe_type in required_ppe:
            detect_classes_names.add(ppe_type)
            detect_classes_names.add(f"no_{ppe_type}")
    else:
        print("No specific classes provided. Using fallback full PPE requirements.")
        required_ppe = DEFAULT_REQUIRED_PPE
        for ppe_type in required_ppe:
            detect_classes_names.add(ppe_type)
            detect_classes_names.add(f"no_{ppe_type}")

    detect_classes_names.add("person")

    # Map class names to indices
    detect_class_indices = []
    model_class_map = {canonicalize(name): idx for idx, name in model.names.items()}
    for name in detect_classes_names:
        if name in model_class_map:
            detect_class_indices.append(model_class_map[name])

    print(f"Model will detect the following classes: {[model.names[i] for i in detect_class_indices]}")

    # Initialize camera processors
    camera_processors = []
    for i, source in enumerate(video_sources):
        try:
            tracker = DeepSort(max_age=70, n_init=3)
            processor = CameraProcessor(
                camera_id=i+1,
                source=source,
                model=model,
                tracker=tracker,
                args=args,
                required_ppe=required_ppe,
                detect_class_indices=detect_class_indices
            )
            camera_processors.append(processor)
            print(f"Camera {i+1} initialized: {source}")
        except Exception as e:
            print(f"Error initializing camera {i+1} ({source}): {e}")

    if not camera_processors:
        print("No cameras could be initialized. Exiting.")
        return

    # Calculate grid layout
    rows, cols = calculate_grid_layout(len(camera_processors))

    # Use first camera's properties as base for output
    output_width = args.output_width if args.output_width else 1920
    output_height = args.output_height if args.output_height else 1080
    output_fps = camera_processors[0].fps

    # Calculate cell dimensions
    cell_width = output_width // cols
    cell_height = output_height // rows

    # Setup video writer
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(args.output, fourcc, output_fps, (output_width, output_height))

    print(f"Output: {output_width}x{output_height} @ {output_fps} FPS")
    print(f"Grid layout: {rows}x{cols}")
    print("Processing started. Press 'q' to quit.")

    # Main processing loop
    frame_count = 0
    while True:
        # Create blank canvas for combined output
        combined_frame = np.zeros((output_height, output_width, 3), dtype=np.uint8)

        all_frames_valid = True

        # Process each camera
        for idx, processor in enumerate(camera_processors):
            frame = processor.process_frame()

            if frame is None:
                all_frames_valid = False
                break

            # Calculate position in grid
            row = idx // cols
            col = idx % cols

            # Resize frame to fit cell
            resized_frame = resize_frame_to_fit(frame, cell_width, cell_height)

            # Place frame in grid
            y_start = row * cell_height
            x_start = col * cell_width
            combined_frame[y_start:y_start+cell_height, x_start:x_start+cell_width] = resized_frame

        if not all_frames_valid:
            print("One or more cameras stopped. Ending processing.")
            break

        # Display and write output
        cv2_imshow(combined_frame)
        out.write(combined_frame)

        frame_count += 1
        if frame_count % 30 == 0:
            print(f"Processed {frame_count} frames...")

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # Cleanup
    for processor in camera_processors:
        processor.release()
    out.release()
    cv2.destroyAllWindows()

    print(f"Processing complete. Output video saved to {args.output}")
    print(f"Total frames processed: {frame_count}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Multi-Camera PPE Detection using YOLOv8 and DeepSort.")

    # Model settings
    parser.add_argument("--model", type=str, default="/content/drive/MyDrive/Models/complete_model_175_epoch.pt",
                        help="Path to the YOLO model file.")

    # Video input settings
    parser.add_argument("--video", type=str, default="/content/drive/MyDrive/client_video/TKIL/TKIL2.mp4",
                        help="Path to single video file, webcam index (e.g., 0), or RTSP URL.")
    parser.add_argument("--cameras", nargs='*',
                        help="Multiple camera sources (files, webcam indices, or RTSP URLs). Example: --cameras 0 1 rtsp://camera3")

    # Output settings
    parser.add_argument("--output", type=str, default="output_video.mp4",
                        help="Path to save the output video file.")
    parser.add_argument("--output-width", type=int, default=1920,
                        help="Output video width (default: 1920)")
    parser.add_argument("--output-height", type=int, default=1080,
                        help="Output video height (default: 1080)")
    parser.add_argument("--log", type=str, default="log.txt",
                        help="Path to save the violation log file. Set to '' to disable.")

    # Detection settings
    parser.add_argument("--conf", type=float, default=0.3,
                        help="Confidence threshold for object detection.")
    parser.add_argument("--iou", type=float, default=0.5,
                        help="IoU threshold for non-maximum suppression.")
    parser.add_argument("--classes", nargs='*',
                        default=["helmet", "shoes", "goggles", "safety_vest", "pvc_suit", "Safety_Gloves"],
                        help="A list of specific classes to check for.")

    # ============================================================================
    # EXAMPLE USAGE SCENARIOS - Uncomment ONE line below to use
    # ============================================================================

    # Example 1: Single video file
    #args = parser.parse_args(args=["--video", "/content/drive/MyDrive/client_video/Berger/WITH-PPE.mp4"])

    # Example 2: Single webcam (index 0)
    # args = parser.parse_args(args=["--video", "0"])

    # Example 3: Single webcam with custom output
    # args = parser.parse_args(args=["--video", "0", "--output", "webcam_output.mp4"])

    # Example 4: Single RTSP camera
    # args = parser.parse_args(args=["--video", "rtsp://192.168.1.100:554/stream"])

    # Example 5: Two webcams (0 and 1)
    # args = parser.parse_args(args=["--cameras", "0", "1"])

    # Example 6: Multiple video files
    args = parser.parse_args(args=[
        "--cameras",
        "/content/drive/MyDrive/client_video/TKIL/TKIL2.mp4",
        "/content/drive/MyDrive/client_video/TKIL/TKIL2.mp4",
        "--output-width", "1920",
        "--output-height", "1080"
     ])

    # Example 7: Mixed sources (webcam + video file)
    # args = parser.parse_args(args=[
    #     "--cameras",
    #     "0",
    #     "/content/drive/MyDrive/client_video/Berger/WITH-PPE.mp4"
    # ])

    # Example 8: Mixed sources (2 webcams + RTSP camera)
    # args = parser.parse_args(args=[
    #     "--cameras",
    #     "0",
    #     "1",
    #     "rtsp://192.168.1.100:554/stream"
    # ])

    # Example 9: Four RTSP cameras
    # args = parser.parse_args(args=[
    #     "--cameras",
    #     "rtsp://192.168.1.100:554/stream",
    #     "rtsp://192.168.1.101:554/stream",
    #     "rtsp://192.168.1.102:554/stream",
    #     "rtsp://192.168.1.103:554/stream"
    # ])

    # Example 10: Multiple cameras with custom settings
    # args = parser.parse_args(args=[
    #     "--cameras", "0", "1",
    #     "--output", "multi_camera_output.mp4",
    #     "--output-width", "3840",
    #     "--output-height", "2160",
    #     "--conf", "0.4",
    #     "--log", "violations_log.txt"
    # ])

    # Example 11: Specific PPE items only (helmet and vest)
    # args = parser.parse_args(args=[
    #     "--video", "0",
    #     "--classes", "helmet", "safety_vest"
    # ])

    # Example 12: Multiple cameras with specific PPE requirements
    # args = parser.parse_args(args=[
    #     "--cameras", "0", "1", "rtsp://192.168.1.100:554/stream",
    #     "--classes", "helmet", "safety_vest", "goggles",
    #     "--conf", "0.35",
    #     "--output", "factory_monitoring.mp4"
    # ])

    main(args)